Repository SAE-S5-01-Developpement-avance/PathPilot-android-client, pull requests merged in 2025-02, with the labels that each got.

#77 Feat/12 start itinerary
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/ServiceFactory.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/Home.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/AddClient.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/Client.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/ClientArrayAdapter.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/ClientCategory.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/ClientService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/FragmentClients.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/AddItinerary.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/FragmentItineraries.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/InfoItinerary.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/Itinerary.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/ItineraryService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/PlayerItinerary.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/routes/IRouteService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/routes/Route.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/routes/RouteService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/login/Login.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/login/LoginService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/map/CurrentPosition.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/map/MapSelection.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/signup/SignUp.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/signup/SignUpService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/util/LocationNameProvider.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/util/Parser.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/util/Popup.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/util/VolleyErrorHandler.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/util/popup/DialogButton.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/util/popup/Popup.java
  app/src/main/res/drawable/icon_client_visited.xml
  app/src/main/res/drawable/icon_detail_client.xml
  app/src/main/res/drawable/icon_detail_client_bg.xml
  app/src/main/res/drawable/icon_pause.xml
  app/src/main/res/drawable/icon_setting_itinerary_client.xml
  app/src/main/res/drawable/icon_start.xml
  app/src/main/res/drawable/icon_stop.xml
  app/src/main/res/layout/component_header_back_icon.xml
  app/src/main/res/layout/view_create_itinerary.xml
  app/src/main/res/layout/view_info_itineray.xml
  app/src/main/res/layout/view_map_selection.xml
  app/src/main/res/layout/view_player_itinerary.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/fr/iut_rodez/pathpilot_android_client/util/ParserTest.java
  gradle/libs.versions.toml
  settings.gradle
Labels: User Story

#88 feat: add loading state management for pagination
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/ClientService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/FragmentClients.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/IClientService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/FragmentItineraries.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/IItineraryService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/ItineraryService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/routes/FragmentRoutes.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/routes/service/IRouteService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/routes/service/RouteService.java
Labels: bug

#82 Fix/70 get optimum itinerary
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/Home.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/ClientService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/IClientService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/clients/entity/Client.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/AddItinerary.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/FragmentItineraries.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/IItineraryService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/ItineraryService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/SaveItinerary.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/home/itinerary/entity/Itinerary.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/login/ILoginService.java
  app/src/main/java/fr/iut_rodez/pathpilot_android_client/signup/ISignUpService.java
  app/src/main/res/layout/view_save_itinerary.xml
  app/src/main/res/menu/itinerary_context_menu.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
  gradle/libs.versions.toml
Labels: feature
